src/Entity/Guest.php
<?php

namespace App\Entity;

use App\Repository\GuestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GuestRepository::class)]
class Guest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $table_number;

    #[ORM\OneToMany(mappedBy: 'guest', targetEntity: Command::class)]
    private $commands;

    public function __construct()
    {
        $this->commands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTableNumber(): ?int
    {
        return $this->table_number;
    }

    public function setTableNumber(?int $table_number): self
    {
        $this->table_number = $table_number;

        return $this;
    }



    public function __toString()
    {
        return $this->getTableNumber()." : ".$this->getDescription();
    }

    /**
     * @return Collection<int, Command>
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands[] = $command;
            $command->setGuest($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->removeElement($command)) {
            // set the owning side to null (unless already changed)
            if ($command->getGuest() === $this) {
                $command->setGuest(null);
            }
        }

        return $this;
    }
}

src/Form/GuestType.php
<?php

namespace App\Form;

use App\Entity\Guest;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GuestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('table_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Guest::class,
        ]);
    }
}

src/Controller/GuestController.php
<?php

namespace App\Controller;

use App\Entity\Guest;
use App\Form\GuestType;
use App\Repository\GuestRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/guest')]
class GuestController extends AbstractController
{
    #[Route('/', name: 'app_guest_index', methods: ['GET'])]
    public function index(GuestRepository $guestRepository): Response
    {
        return $this->render('guest/index.html.twig', [
            'guests' => $guestRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_guest_new', methods: ['GET', 'POST'])]
    public function new(Request $request, GuestRepository $guestRepository): Response
    {
        $guest = new Guest();
        $form = $this->createForm(GuestType::class, $guest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $guestRepository->add($guest);
            return $this->redirectToRoute('app_guest_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('guest/new.html.twig', [
            'guest' => $guest,
            'form' => $form,
        ]);
    }

    #[Route('/{id}</d+>', name: 'app_guest_show', methods: ['GET'])]
    public function show(Guest $guest): Response
    {
        return $this->render('guest/show.html.twig', [
            'guest' => $guest,
        ]);
    }

    #[Route('/{id}</d+>/edit', name: 'app_guest_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Guest $guest, GuestRepository $guestRepository): Response
    {
        $form = $this->createForm(GuestType::class, $guest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $guestRepository->add($guest);
            return $this->redirectToRoute('app_guest_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('guest/edit.html.twig', [
            'guest' => $guest,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_guest_delete', methods: ['POST'])]
    public function delete(Request $request, Guest $guest, GuestRepository $guestRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$guest->getId(), $request->request->get('_token'))) {
            $guestRepository->remove($guest);
        }

        return $this->redirectToRoute('app_guest_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/guest/_delete_form.html.twig
<form method="post" action="{{ path('app_guest_delete', {'id': guest.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ guest.id) }}">
    <button class="btn">{% trans %}Delete {% endtrans %}</button>
</form>

templates/guest/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Guest{% endblock %}
{% block body %}
    <h1>{% trans %} Edit Guest{% endtrans %}</h1>

    {{ include('guest/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_guest_index') }}"> {% trans %} back to list {% endtrans %}</a>
 
    {{ include('guest/_delete_form.html.twig') }}
{% endblock %}

templates/guest/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Guest index{% endblock %}

{% block body %}
    <h1>Guest index</h1>
{% include 'tab.html.twig' %}
    <table class="table">
        <thead>
            <tr>
 <th>{% trans %}Id{% endtrans %} </th>
 <th>{% trans %}Name{% endtrans %} </th>
 <th>{% trans %}Description{% endtrans %} </th>
 <th>{% trans %}Table_number{% endtrans %} </th>
                <th>{% trans %}actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for guest in guests %}
            <tr>
                <td> {{ guest.id }}</td>
                <td> {{ guest.name }}</td>
                <td> {{ guest.description }}</td>
                <td> {{ guest.tableNumber }}</td>
                <td>
                    <a href="{{ path('app_guest_show', {'id': guest.id}) }}">{% trans %}show{% endtrans %}</a>
                    <a href="{{ path('app_guest_edit', {'id': guest.id}) }}">{% trans %}edit{% endtrans %}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">{% trans %}no records found{% endtrans %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_guest_new') }}">{% trans %}Create new{% endtrans %}</a>
{% endblock %}

templates/guest/new.html.twig
 {% extends 'base.html.twig' %}

{% block title %}New Guest{% endblock %}

{% block body %}
    <h1>{% trans %}Create new <{% endtrans %}?= $entity_class_name ?></h1>

    {{ include('guest/_form.html.twig') }}

    <a href="{{ path('app_guest_index') }}">{% trans %}back to list {% endtrans %}</a>
{% endblock %}

templates/guest/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Guest{% endblock %}

{% block body %}
    <h1>Guest</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ guest.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ guest.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ guest.description }}</td>
            </tr>
            <tr>
                <th>Table_number</th>
                <td>{{ guest.tableNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_guest_index') }}">{% trans %}back to list{% endtrans %}</a>

    <a href="{{ path('app_guest_edit', {'id': guest.id}) }}">{% trans %}edit{% endtrans %}</a>

    {{ include('guest/_delete_form.html.twig') }}
{% endblock %}